baseURL = 'https://non-neutralzero.github.io/notebook/'
languageCode = 'en-us'
title = 'Digital Notebook NonNeutralZero'
theme = 'hugo-book'

# Syntax highlighting
pygmentsCodeFences = true 
pygmentsUseClasses = false  
pygmentsStyle = "nord"  

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Non-NeutralZero"
  weight = 10

[[menu.after]]
  name = "NonNeutralZero"
  url = "https://nonneutralzero.com"
  weight = 20

[[menu.after]]
  name = "Linktree"
  url = "https://linktr.ee/nonneutralzero"
  weight = 30

[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com/Non-NeutralZero/notebook'
  BookSection = 'docs'
  BookCommitPath = 'commit'
  BookSearch = true
  BookDateFormat = "Jan 2, 2006"

[params.extra]
copyright = "© 2026. NonNeutralZero."
poweredby = true