name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  HUGO_VERSION: "0.146.6"
  HUGO_ENVIRONMENT: "production"
  HUGO_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pr_closed_merged: ${{ steps.pr_status.outputs.pr_closed_merged }}
    steps:
      - id: pr_status
        if: github.event.pull_request
        run: echo "pr_closed_merged=${{ github.event.pull_request.closed_at || github.event.pull_request.merged }}" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: ./public
          retention-days: 1

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
